-- ============================================================
-- PLATAFORMA LIVIU — Migración 15: categorías de alimentos y
-- exclusiones del cliente (base para la futura generación
-- automática de dietas por macros).
--  · categoria en alimentos: proteina/carbohidrato/grasa/verdura/
--    fruta/lacteo/legumbre/otro. Se categoriza automáticamente la
--    base de 402 alimentos de Liviu; los que cree el propio
--    entrenador quedan sin categoría hasta que la asigne.
--  · alimentos_excluidos: alimentos que un cliente no quiere ver
--    en su dieta (alergias, cosas que no le gustan). El cliente
--    gestiona los suyos; el entrenador ve/gestiona los de
--    cualquier cliente.
-- ============================================================

alter table public.alimentos
  add column if not exists categoria text
  check (categoria is null or categoria in ('proteina','carbohidrato','grasa','verdura','fruta','lacteo','legumbre','otro'));

-- ------------------------------------------------------------
-- Backfill: categoriza los 402 alimentos base de Liviu
-- ------------------------------------------------------------
update public.alimentos a set categoria = v.categoria
from (values
  ('Arepa', 'carbohidrato'),
  ('Arroz blanco (crudo)', 'carbohidrato'),
  ('Arroz integral (crudo)', 'carbohidrato'),
  ('Copos de avena', 'carbohidrato'),
  ('Azúcar blanco', 'otro'),
  ('Azúcar moreno', 'otro'),
  ('Alubias', 'legumbre'),
  ('Alubias cocidas', 'legumbre'),
  ('Alcaparras en vinagre', 'otro'),
  ('Barritas cereales integrales', 'carbohidrato'),
  ('Bebida de avena', 'lacteo'),
  ('Bebida de avellanas', 'lacteo'),
  ('Base de pizza congelada', 'carbohidrato'),
  ('Base pizza fresca', 'carbohidrato'),
  ('Base pizza cereales y semillas', 'carbohidrato'),
  ('Boniato', 'carbohidrato'),
  ('Colacao', 'otro'),
  ('Castañas', 'carbohidrato'),
  ('Chía', 'grasa'),
  ('Chocolate negro (70-85%)', 'otro'),
  ('Chocolate negro (>85%)', 'otro'),
  ('Corn flakes 0%', 'carbohidrato'),
  ('Cereales de avena crunchy', 'carbohidrato'),
  ('Crackers espelta', 'carbohidrato'),
  ('Crema de pistacho (comercial)', 'grasa'),
  ('Crema de verduras', 'verdura'),
  ('Cereales de espelta', 'carbohidrato'),
  ('Dátil', 'fruta'),
  ('Espaguetis', 'carbohidrato'),
  ('Flan de huevo', 'otro'),
  ('Flan vainilla', 'otro'),
  ('Focaccia (mercadona)', 'carbohidrato'),
  ('Fideos', 'carbohidrato'),
  ('Guisantes', 'legumbre'),
  ('Guisantes cocidos', 'legumbre'),
  ('Garbanzos', 'legumbre'),
  ('Hummus', 'legumbre'),
  ('Harina de avena', 'carbohidrato'),
  ('Harina trigo', 'carbohidrato'),
  ('Harina trigo integral', 'carbohidrato'),
  ('Harina maíz', 'carbohidrato'),
  ('Harina centeno', 'carbohidrato'),
  ('Kefir', 'lacteo'),
  ('Kombucha', 'otro'),
  ('Konjac', 'otro'),
  ('Leche semi', 'lacteo'),
  ('Leche desnatada', 'lacteo'),
  ('Leche entera', 'lacteo'),
  ('Leche sin lactosa', 'lacteo'),
  ('Leche condensada', 'lacteo'),
  ('Mariñeiras con aove (rebanadas de pan)', 'carbohidrato'),
  ('Macarrones (pasta)', 'carbohidrato'),
  ('Miel', 'otro'),
  ('Mermelada azucarada', 'otro'),
  ('Mermelada baja en calorías', 'otro'),
  ('Mermelada 0%', 'otro'),
  ('Membrillo azucarado', 'otro'),
  ('Membrillo sin azúcares añadidos', 'otro'),
  ('Muesli', 'carbohidrato'),
  ('Muesli crunchy (hacendado)', 'carbohidrato'),
  ('Ñoquis', 'carbohidrato'),
  ('Ñoquis quesos', 'carbohidrato'),
  ('Noodles arroz', 'carbohidrato'),
  ('Natilla chocolate', 'otro'),
  ('Natilla vainilla', 'otro'),
  ('Nesquik', 'otro'),
  ('Orejones', 'fruta'),
  ('Pan blanco de molde (Carrefour rústico)', 'carbohidrato'),
  ('Pan blanco de trigo', 'carbohidrato'),
  ('Pan blanco de trigo sin sal', 'carbohidrato'),
  ('Pan blanco tostado', 'carbohidrato'),
  ('Pan blanco tostado sin sal', 'carbohidrato'),
  ('Pan de centeno', 'carbohidrato'),
  ('Pan de pasas', 'carbohidrato'),
  ('Pan de pita', 'carbohidrato'),
  ('Pan de trigo y de centeno', 'carbohidrato'),
  ('Pan de viena', 'carbohidrato'),
  ('Pan integral de molde', 'carbohidrato'),
  ('Pan integral de trigo', 'carbohidrato'),
  ('Pan integral tostado', 'carbohidrato'),
  ('Pan multicereales', 'carbohidrato'),
  ('Pan rallado', 'carbohidrato'),
  ('Pan wasa', 'carbohidrato'),
  ('Pan hamburguesa (carrefour)', 'carbohidrato'),
  ('Pan bagel', 'carbohidrato'),
  ('Panecillos de aceite de oliva', 'carbohidrato'),
  ('Pasta de espinacas', 'carbohidrato'),
  ('Pasta de lentejas', 'legumbre'),
  ('Pasta de garbanzos', 'legumbre'),
  ('Pasta integral', 'carbohidrato'),
  ('Pasta vegetal', 'carbohidrato'),
  ('Pasta avena y maíz', 'carbohidrato'),
  ('Patata', 'carbohidrato'),
  ('Pepinillos', 'verdura'),
  ('Piadina (prozis)', 'carbohidrato'),
  ('Pisto de verduras', 'verdura'),
  ('Palitos de espelta', 'carbohidrato'),
  ('Picos', 'carbohidrato'),
  ('Picos integrales', 'carbohidrato'),
  ('Quinoa', 'carbohidrato'),
  ('Regañás (hacendado)', 'carbohidrato'),
  ('Salsa mexicana (hacendado)', 'otro'),
  ('Salsa de tomate', 'otro'),
  ('Sésamo', 'grasa'),
  ('Tortellini de carne', 'carbohidrato'),
  ('Tortellini de queso', 'carbohidrato'),
  ('Tortitas de maíz', 'carbohidrato'),
  ('Tortitas de arroz', 'carbohidrato'),
  ('Tortitas de arroz y legumbres', 'carbohidrato'),
  ('Tortitas de avena', 'carbohidrato'),
  ('Tortillas integrales', 'carbohidrato'),
  ('Tortillas de trigo', 'carbohidrato'),
  ('Tortillas de avena', 'carbohidrato'),
  ('Uva pasa', 'fruta'),
  ('Yogur desnatado natural', 'lacteo'),
  ('Yogur entero natural', 'lacteo'),
  ('Yogur líquido natural', 'lacteo'),
  ('Zumo de naranja natural', 'fruta'),
  ('Zumo de melocotón', 'fruta'),
  ('Zumo de piña', 'fruta'),
  ('Zumo de cítricos', 'fruta'),
  ('Zumo de no cítricos', 'fruta'),
  ('Crema de arroz', 'carbohidrato'),
  ('Ciclodextrina', 'carbohidrato'),
  ('Maltodextrina', 'carbohidrato'),
  ('Gel energético', 'carbohidrato'),
  ('Anchoa', 'proteina'),
  ('Almejas', 'proteina'),
  ('Almejas al natural (líquido)', 'proteina'),
  ('Atún', 'proteina'),
  ('Atún conserva nat', 'proteina'),
  ('Bacalao', 'proteina'),
  ('Barritas proteícas cookie(myprotein)', 'proteina'),
  ('Bebida de soja', 'lacteo'),
  ('Berberechos', 'proteina'),
  ('Bogavante', 'proteina'),
  ('Boquerones', 'proteina'),
  ('Bonito', 'proteina'),
  ('Caballa', 'proteina'),
  ('Cabracho', 'proteina'),
  ('Calamar', 'proteina'),
  ('Centollo', 'proteina'),
  ('Cerdo,lomo', 'proteina'),
  ('Cerdo, chuleta', 'proteina'),
  ('Carne picada vacuno', 'proteina'),
  ('Carne picada cerdo', 'proteina'),
  ('Carne picada pollo y pavo', 'proteina'),
  ('Cigala', 'proteina'),
  ('Conejo', 'proteina'),
  ('Congrio', 'proteina'),
  ('Cordero', 'proteina'),
  ('Dorada', 'proteina'),
  ('Espirulina', 'proteina'),
  ('Fletán', 'proteina'),
  ('Flan+prot', 'proteina'),
  ('Gallo', 'proteina'),
  ('Gamba', 'proteina'),
  ('Gelatina', 'otro'),
  ('Gelatina +proteína', 'proteina'),
  ('Heura (bocados)', 'proteina'),
  ('Huevo', 'proteina'),
  ('Clara de huevo', 'proteina'),
  ('Callos', 'proteina'),
  ('Cecina', 'proteina'),
  ('Hígado de cerdo', 'proteina'),
  ('Hígado de cordero', 'proteina'),
  ('Hígado de pollo', 'proteina'),
  ('Hígado de ternera', 'proteina'),
  ('Riñones', 'proteina'),
  ('Sesos de cordero', 'proteina'),
  ('Soja texturizada', 'proteina'),
  ('Jurel', 'proteina'),
  ('Jamón cocido', 'proteina'),
  ('Jamón serrano', 'proteina'),
  ('Judías verdes', 'verdura'),
  ('Judías blancas', 'legumbre'),
  ('Langosta', 'proteina'),
  ('Leche proteínas', 'lacteo'),
  ('Lenguado', 'proteina'),
  ('Lomo embuchado', 'proteina'),
  ('Lentejas', 'legumbre'),
  ('Lentejas (cocidas de bote)', 'legumbre'),
  ('Garbanzos (cocidos de bote)', 'legumbre'),
  ('Lubina', 'proteina'),
  ('Mejillones', 'proteina'),
  ('Mejillones en esabeche(escurrido)', 'proteina'),
  ('Mejillones al natural(escurrido)', 'proteina'),
  ('Merluza', 'proteina'),
  ('Mero', 'proteina'),
  ('Mollejas', 'proteina'),
  ('Navaja', 'proteina'),
  ('Natilla+prot', 'proteina'),
  ('Ostra', 'proteina'),
  ('Palometa', 'proteina'),
  ('Percebes', 'proteina'),
  ('Pez espada', 'proteina'),
  ('Pez limón', 'proteina'),
  ('Pollo', 'proteina'),
  ('Pollo, muslo sin piel', 'proteina'),
  ('Pollo, pechuga', 'proteina'),
  ('Pavo, fiambre', 'proteina'),
  ('Pavo, deshuesado, sin piel', 'proteina'),
  ('Pavo, muslo con piel', 'proteina'),
  ('Pavo, pechuga sin piel', 'proteina'),
  ('Pavo, sin piel', 'proteina'),
  ('Pulpo', 'proteina'),
  ('Queso mozzarella', 'lacteo'),
  ('Queso fresco (Burgos)', 'lacteo'),
  ('Queso fresco 0%', 'lacteo'),
  ('Queso parmesano', 'lacteo'),
  ('Queso fresco batido', 'lacteo'),
  ('Queso havarti (normal)', 'lacteo'),
  ('Queso havarti light', 'lacteo'),
  ('Queso feta', 'lacteo'),
  ('Queso cheddar', 'lacteo'),
  ('Queso cottage', 'lacteo'),
  ('Queso emmental', 'lacteo'),
  ('Queso gouda', 'lacteo'),
  ('Queso ricotta', 'lacteo'),
  ('Queso semi mezcla', 'lacteo'),
  ('Queso curado mezcla', 'lacteo'),
  ('Queso de cabra curado (rulo)', 'lacteo'),
  ('Queso de cabra semicurado', 'lacteo'),
  ('Queso en polvo', 'lacteo'),
  ('Quesitos light', 'lacteo'),
  ('Queso azul', 'lacteo'),
  ('Queso de oveja semicurado', 'lacteo'),
  ('Queso de oveja curado (viejo)', 'lacteo'),
  ('Mini babybel', 'lacteo'),
  ('Queso de untar (Philadelphia)', 'lacteo'),
  ('Queso untar light', 'lacteo'),
  ('Rape', 'proteina'),
  ('Raya', 'proteina'),
  ('Requesón', 'lacteo'),
  ('Rodaballo', 'proteina'),
  ('Salsa de soja', 'otro'),
  ('Salmón', 'proteina'),
  ('Salmón ahumado', 'proteina'),
  ('Salmonete', 'proteina'),
  ('Sardinas', 'proteina'),
  ('Sardinas en aceite de oliva', 'proteina'),
  ('Sepia', 'proteina'),
  ('Tempeh', 'proteina'),
  ('Ternera, carne magra', 'proteina'),
  ('Tofu', 'proteina'),
  ('Trucha', 'proteina'),
  ('Tiras de pollo', 'proteina'),
  ('Vieiras', 'proteina'),
  ('Zamburiñas enlatadas', 'proteina'),
  ('Yogur griego ligero', 'lacteo'),
  ('Yogur enriquecido en proteínas sabor natural', 'lacteo'),
  ('Yogur enriquecido en proteínas sabor fresa', 'lacteo'),
  ('Yogur enriquecido en proteínas sabor arándanos', 'lacteo'),
  ('Yogur enriquecido en proteínas sabor vainilla', 'lacteo'),
  ('Yogur enriquecido en proteínas sabor mango', 'lacteo'),
  ('Yogur enriquecido en proteínas sabor caramelo', 'lacteo'),
  ('Yogur enriquecido en proteínas sabor limón', 'lacteo'),
  ('Yogur enriquecido en proteínas sabor straciatella', 'lacteo'),
  ('Yogur líquido enriquecido en proteínas sabor fresa', 'lacteo'),
  ('Yogur líquido enriquecido en proteínas sabor tropical', 'lacteo'),
  ('Yogur líquido enriquecido en proteínas sabor vainilla', 'lacteo'),
  ('Yogur líquido enriquecido en proteínas sabor açai plátano', 'lacteo'),
  ('Yogur líquido enriquecido en proteínas sabor prot coco', 'lacteo'),
  ('Proteína ISO Whey', 'proteina'),
  ('Aceite de coco', 'grasa'),
  ('Aceite de girasol', 'grasa'),
  ('Aceite de oliva', 'grasa'),
  ('AO virgen', 'grasa'),
  ('AOVE', 'grasa'),
  ('A.cacahuete', 'grasa'),
  ('Aceite de colza', 'grasa'),
  ('Aceite de maíz', 'grasa'),
  ('Aceite de nuez', 'grasa'),
  ('Aceite de palma', 'grasa'),
  ('A.semilla de uva', 'grasa'),
  ('Aceite de sésamo', 'grasa'),
  ('Aceite de soja', 'grasa'),
  ('Aguacate', 'grasa'),
  ('Almendras', 'grasa'),
  ('Anacardos', 'grasa'),
  ('Aceitunas verdes', 'grasa'),
  ('Aceitunas negras', 'grasa'),
  ('Avellanas', 'grasa'),
  ('Beicon', 'grasa'),
  ('Cacahuete', 'grasa'),
  ('Crema de cacahuete natural (comercial)', 'grasa'),
  ('Crema de cacahuete (prozis)', 'grasa'),
  ('Crema de pistacho (prozis)', 'grasa'),
  ('Crema de almendras (comercial)', 'grasa'),
  ('Crema de almendras (prozis)', 'grasa'),
  ('Crema de avellanas (BULK)', 'grasa'),
  ('Crema anacardos (BULK)', 'grasa'),
  ('Guacamole', 'grasa'),
  ('Lino', 'grasa'),
  ('Mantequilla con sal', 'grasa'),
  ('Mantequilla sin sal', 'grasa'),
  ('Nuez', 'grasa'),
  ('Piñones', 'grasa'),
  ('Pipas de calabaza (peladas)', 'grasa'),
  ('Pipas de girasol (peladas)', 'grasa'),
  ('Pistacho', 'grasa'),
  ('Yogur griego', 'lacteo'),
  ('Yema de huevo', 'grasa'),
  ('Salsa carbonara', 'otro'),
  ('Salsa boloñesa', 'otro'),
  ('Cous Cous', 'carbohidrato'),
  ('Bebida de almendras 0%', 'lacteo'),
  ('Apio', 'verdura'),
  ('Berros', 'verdura'),
  ('Calabaza', 'verdura'),
  ('Cebolla', 'verdura'),
  ('Cebollino', 'verdura'),
  ('Endibia', 'verdura'),
  ('Escarola', 'verdura'),
  ('Espárrago blanco en conserva', 'verdura'),
  ('Lechuga', 'verdura'),
  ('Lombarda', 'verdura'),
  ('Maíz', 'carbohidrato'),
  ('Nabo', 'verdura'),
  ('Pepino', 'verdura'),
  ('Puerro', 'verdura'),
  ('Rábano', 'verdura'),
  ('Remolacha', 'verdura'),
  ('Rúcula', 'verdura'),
  ('Tomate', 'verdura'),
  ('Tomate cherry', 'verdura'),
  ('Verdolaga', 'verdura'),
  ('Wakame', 'verdura'),
  ('Zanahoria', 'verdura'),
  ('Verduras crudas', 'verdura'),
  ('Acelga', 'verdura'),
  ('Ajo', 'verdura'),
  ('Ajos tiernos', 'verdura'),
  ('Alcachofas', 'verdura'),
  ('Berenjena', 'verdura'),
  ('Brocoli', 'verdura'),
  ('Calabacín', 'verdura'),
  ('Cardo', 'verdura'),
  ('Coles de bruselas', 'verdura'),
  ('Coliflor', 'verdura'),
  ('Espárrago blanco fresco', 'verdura'),
  ('Espárrago verde fresco', 'verdura'),
  ('Espinacas', 'verdura'),
  ('Grelos', 'verdura'),
  ('Habas', 'legumbre'),
  ('Kale', 'verdura'),
  ('Ñame', 'carbohidrato'),
  ('Pimiento rojo', 'verdura'),
  ('Pimiento verde', 'verdura'),
  ('Pimiento enlatado', 'verdura'),
  ('Repollo', 'verdura'),
  ('Verduras cocinadas', 'verdura'),
  ('Limón', 'fruta'),
  ('Lima', 'fruta'),
  ('Mandarina', 'fruta'),
  ('Mora', 'fruta'),
  ('Naranja', 'fruta'),
  ('Piña', 'fruta'),
  ('Uva negra', 'fruta'),
  ('Piña en su jugo', 'fruta'),
  ('Pomelo', 'fruta'),
  ('Uva blanca', 'fruta'),
  ('Frutas cítricas', 'fruta'),
  ('Albaricoque', 'fruta'),
  ('Arándanos', 'fruta'),
  ('Caqui', 'fruta'),
  ('Cerezas', 'fruta'),
  ('Chirimoya', 'fruta'),
  ('Ciruela', 'fruta'),
  ('Ciruela pasa', 'fruta'),
  ('Frambuesas', 'fruta'),
  ('Granada', 'fruta'),
  ('Grosella', 'fruta'),
  ('Guayaba', 'fruta'),
  ('Lichis', 'fruta'),
  ('Manzana', 'fruta'),
  ('Mango', 'fruta'),
  ('Melocotón', 'fruta'),
  ('Sandía', 'fruta'),
  ('Melón', 'fruta'),
  ('Nectarina', 'fruta'),
  ('Níspero', 'fruta'),
  ('Paraguaya', 'fruta'),
  ('Papaya', 'fruta'),
  ('Pera', 'fruta'),
  ('Xoconostle', 'fruta'),
  ('Frutas no cítricas', 'fruta'),
  ('Añadir alimento', 'otro'),
  ('Evocarbs 2.0 (HSN)', 'carbohidrato'),
  ('Amilopectina', 'carbohidrato'),
  ('Caseína', 'proteina'),
  ('Dextrosa', 'carbohidrato'),
  ('Palatinosa', 'carbohidrato'),
  ('Carbonox', 'carbohidrato'),
  ('Vitargo', 'carbohidrato'),
  ('Piadinas', 'carbohidrato'),
  ('Patatas enteras en tarro', 'carbohidrato'),
  ('Gelatina zero', 'otro'),
  ('Mozzarella light', 'lacteo'),
  ('Yogur Alpro sabor coco', 'lacteo'),
  ('Pechuga de pollo 99%', 'proteina'),
  ('Tostadas de desayuno (sin gluten) Noglut', 'carbohidrato')
) as v(nombre, categoria)
where a.nombre = v.nombre and a.creado_por is null;

-- ------------------------------------------------------------
-- Exclusiones del cliente
-- ------------------------------------------------------------
create table public.alimentos_excluidos (
  id uuid primary key default gen_random_uuid(),
  cliente_id uuid not null references public.profiles (id) on delete cascade,
  alimento_id uuid not null references public.alimentos (id) on delete cascade,
  creado_en timestamptz not null default now(),
  unique (cliente_id, alimento_id)
);

create index idx_alimentos_excluidos_cliente on public.alimentos_excluidos (cliente_id);

alter table public.alimentos_excluidos enable row level security;

create policy "entrenador todo" on public.alimentos_excluidos for all
  using (es_entrenador()) with check (es_entrenador());

create policy "cliente gestiona sus exclusiones" on public.alimentos_excluidos for all
  using (cliente_id = auth.uid()) with check (cliente_id = auth.uid());
