-- ============================================================
-- PLATAFORMA LIVIU — Migración 3: semilla de la biblioteca
-- de ejercicios (~150 ejercicios comunes, en español).
-- creado_por = null => biblioteca base, visible para todos.
-- ============================================================

insert into public.ejercicios (nombre, grupo_muscular, material) values
-- ------------------------- PECHO -------------------------
('Press banca', 'Pecho', 'Barra'),
('Press banca agarre cerrado', 'Pecho', 'Barra'),
('Press inclinado con barra', 'Pecho', 'Barra'),
('Press declinado con barra', 'Pecho', 'Barra'),
('Press banca con mancuernas', 'Pecho', 'Mancuernas'),
('Press inclinado con mancuernas', 'Pecho', 'Mancuernas'),
('Aperturas con mancuernas', 'Pecho', 'Mancuernas'),
('Aperturas inclinadas con mancuernas', 'Pecho', 'Mancuernas'),
('Aperturas en polea (cruce de poleas)', 'Pecho', 'Polea'),
('Cruce de poleas bajo', 'Pecho', 'Polea'),
('Press en máquina', 'Pecho', 'Máquina'),
('Contractora (peck deck)', 'Pecho', 'Máquina'),
('Fondos en paralelas', 'Pecho', 'Peso corporal'),
('Flexiones', 'Pecho', 'Peso corporal'),
('Flexiones con lastre', 'Pecho', 'Lastre'),
('Flexiones declinadas', 'Pecho', 'Peso corporal'),
('Press de suelo con mancuernas', 'Pecho', 'Mancuernas'),
('Pullover con mancuerna', 'Pecho', 'Mancuerna'),

-- ------------------------- ESPALDA -------------------------
('Dominadas', 'Espalda', 'Peso corporal'),
('Dominadas lastradas', 'Espalda', 'Lastre'),
('Dominadas supinas (chin-up)', 'Espalda', 'Peso corporal'),
('Dominadas asistidas en máquina', 'Espalda', 'Máquina'),
('Jalón al pecho', 'Espalda', 'Polea'),
('Jalón al pecho agarre cerrado', 'Espalda', 'Polea'),
('Jalón al pecho agarre supino', 'Espalda', 'Polea'),
('Remo con barra', 'Espalda', 'Barra'),
('Remo Pendlay', 'Espalda', 'Barra'),
('Remo con mancuerna a una mano', 'Espalda', 'Mancuerna'),
('Remo en punta (T-bar)', 'Espalda', 'Barra'),
('Remo en polea baja (Gironda)', 'Espalda', 'Polea'),
('Remo en máquina', 'Espalda', 'Máquina'),
('Remo en máquina agarre neutro', 'Espalda', 'Máquina'),
('Peso muerto', 'Espalda', 'Barra'),
('Rack pull (peso muerto parcial)', 'Espalda', 'Barra'),
('Pull-over en polea alta', 'Espalda', 'Polea'),
('Face pull', 'Espalda', 'Polea'),
('Encogimientos de trapecio con barra', 'Espalda', 'Barra'),
('Encogimientos de trapecio con mancuernas', 'Espalda', 'Mancuernas'),
('Hiperextensiones lumbares', 'Espalda', 'Banco'),
('Remo invertido en barra', 'Espalda', 'Peso corporal'),

-- ------------------------- HOMBRO -------------------------
('Press militar de pie', 'Hombro', 'Barra'),
('Press militar sentado', 'Hombro', 'Barra'),
('Press de hombro con mancuernas', 'Hombro', 'Mancuernas'),
('Press Arnold', 'Hombro', 'Mancuernas'),
('Press de hombro en máquina', 'Hombro', 'Máquina'),
('Push press', 'Hombro', 'Barra'),
('Elevaciones laterales', 'Hombro', 'Mancuernas'),
('Elevaciones laterales en polea', 'Hombro', 'Polea'),
('Elevaciones laterales en máquina', 'Hombro', 'Máquina'),
('Elevaciones frontales con mancuernas', 'Hombro', 'Mancuernas'),
('Elevaciones frontales con disco', 'Hombro', 'Disco'),
('Pájaros (deltoide posterior)', 'Hombro', 'Mancuernas'),
('Deltoide posterior en máquina', 'Hombro', 'Máquina'),
('Deltoide posterior en polea (cruces inversos)', 'Hombro', 'Polea'),
('Remo al mentón', 'Hombro', 'Barra'),
('Press tras nuca', 'Hombro', 'Barra'),

-- ------------------------- BÍCEPS -------------------------
('Curl de bíceps con barra', 'Bíceps', 'Barra'),
('Curl de bíceps con barra Z', 'Bíceps', 'Barra Z'),
('Curl de bíceps con mancuernas', 'Bíceps', 'Mancuernas'),
('Curl alterno con mancuernas', 'Bíceps', 'Mancuernas'),
('Curl martillo', 'Bíceps', 'Mancuernas'),
('Curl inclinado con mancuernas', 'Bíceps', 'Mancuernas'),
('Curl concentrado', 'Bíceps', 'Mancuerna'),
('Curl en banco Scott', 'Bíceps', 'Barra Z'),
('Curl en polea baja', 'Bíceps', 'Polea'),
('Curl en polea con cuerda', 'Bíceps', 'Polea'),
('Curl araña', 'Bíceps', 'Barra Z'),
('Curl de antebrazo (muñeca)', 'Bíceps', 'Barra'),

-- ------------------------- TRÍCEPS -------------------------
('Press francés con barra Z', 'Tríceps', 'Barra Z'),
('Press francés con mancuernas', 'Tríceps', 'Mancuernas'),
('Extensión de tríceps en polea alta', 'Tríceps', 'Polea'),
('Extensión de tríceps con cuerda', 'Tríceps', 'Polea'),
('Extensión de tríceps sobre la cabeza en polea', 'Tríceps', 'Polea'),
('Extensión de tríceps con mancuerna a una mano', 'Tríceps', 'Mancuerna'),
('Fondos entre bancos', 'Tríceps', 'Peso corporal'),
('Fondos en paralelas (tríceps)', 'Tríceps', 'Peso corporal'),
('Fondos lastrados', 'Tríceps', 'Lastre'),
('Patada de tríceps con mancuerna', 'Tríceps', 'Mancuerna'),
('Press banca agarre cerrado (tríceps)', 'Tríceps', 'Barra'),
('Extensión de tríceps en máquina', 'Tríceps', 'Máquina'),

-- ------------------------- PIERNA -------------------------
('Sentadilla', 'Pierna', 'Barra'),
('Sentadilla frontal', 'Pierna', 'Barra'),
('Sentadilla goblet', 'Pierna', 'Mancuerna'),
('Sentadilla búlgara', 'Pierna', 'Mancuernas'),
('Sentadilla en multipower', 'Pierna', 'Multipower'),
('Sentadilla hack', 'Pierna', 'Máquina'),
('Sentadilla sissy', 'Pierna', 'Peso corporal'),
('Prensa de piernas', 'Pierna', 'Máquina'),
('Prensa horizontal', 'Pierna', 'Máquina'),
('Zancadas con mancuernas', 'Pierna', 'Mancuernas'),
('Zancadas con barra', 'Pierna', 'Barra'),
('Zancadas caminando', 'Pierna', 'Mancuernas'),
('Subida al cajón (step-up)', 'Pierna', 'Mancuernas'),
('Extensión de cuádriceps', 'Pierna', 'Máquina'),
('Curl femoral tumbado', 'Pierna', 'Máquina'),
('Curl femoral sentado', 'Pierna', 'Máquina'),
('Curl femoral de pie', 'Pierna', 'Máquina'),
('Curl nórdico', 'Pierna', 'Peso corporal'),
('Peso muerto rumano', 'Pierna', 'Barra'),
('Peso muerto rumano con mancuernas', 'Pierna', 'Mancuernas'),
('Peso muerto piernas rígidas', 'Pierna', 'Barra'),
('Buenos días', 'Pierna', 'Barra'),
('Gemelo de pie en máquina', 'Pierna', 'Máquina'),
('Gemelo de pie con barra', 'Pierna', 'Barra'),
('Gemelo sentado', 'Pierna', 'Máquina'),
('Gemelo en prensa', 'Pierna', 'Máquina'),
('Aductores en máquina', 'Pierna', 'Máquina'),
('Abductores en máquina', 'Pierna', 'Máquina'),

-- ------------------------- GLÚTEO -------------------------
('Hip thrust con barra', 'Glúteo', 'Barra'),
('Hip thrust en máquina', 'Glúteo', 'Máquina'),
('Puente de glúteo', 'Glúteo', 'Peso corporal'),
('Puente de glúteo con disco', 'Glúteo', 'Disco'),
('Patada de glúteo en polea', 'Glúteo', 'Polea'),
('Patada de glúteo en máquina', 'Glúteo', 'Máquina'),
('Peso muerto sumo', 'Glúteo', 'Barra'),
('Abducción de cadera en polea', 'Glúteo', 'Polea'),
('Sentadilla sumo con mancuerna', 'Glúteo', 'Mancuerna'),
('Hiperextensión con foco en glúteo', 'Glúteo', 'Banco'),
('Frog pump', 'Glúteo', 'Peso corporal'),
('Monster walk con banda', 'Glúteo', 'Banda elástica'),

-- ------------------------- CORE -------------------------
('Plancha', 'Core', 'Peso corporal'),
('Plancha lateral', 'Core', 'Peso corporal'),
('Plancha con lastre', 'Core', 'Lastre'),
('Crunch abdominal', 'Core', 'Peso corporal'),
('Crunch en polea alta', 'Core', 'Polea'),
('Crunch en máquina', 'Core', 'Máquina'),
('Elevaciones de piernas colgado', 'Core', 'Peso corporal'),
('Elevaciones de rodillas colgado', 'Core', 'Peso corporal'),
('Elevaciones de piernas tumbado', 'Core', 'Peso corporal'),
('Rueda abdominal', 'Core', 'Rueda'),
('Dead bug', 'Core', 'Peso corporal'),
('Bird dog', 'Core', 'Peso corporal'),
('Pallof press', 'Core', 'Polea'),
('Rotación en polea (leñador)', 'Core', 'Polea'),
('Russian twist', 'Core', 'Disco'),
('Mountain climbers', 'Core', 'Peso corporal'),
('Hollow hold', 'Core', 'Peso corporal'),
('Abdominales en banco declinado', 'Core', 'Banco');
